name: route_directions
description: A dart package to get polyline points by either passing the coordinates or google encoded polyline string
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.5.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
